//
//  MagazineDetailInteractor.swift
//  PdfSample
//
//  Created by 60058232 on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MagazineDetailBusinessLogic
{
	func fetchMagazine(request: MagazineDetail.FetchMagazine.Request)
}

protocol MagazineDetailDataStore
{
	var id: Int? { get set }
	var title: String? { get set }
	var pdfUrl: String? { get set }
}

class MagazineDetailInteractor: MagazineDetailBusinessLogic, MagazineDetailDataStore
{
	var presenter: MagazineDetailPresentationLogic?
	var magazineWorker: MagazineWorker = MagazineWorker(magazineStore: MagazineStore())

	var id: Int?
	var title: String?
	var pdfUrl: String?

	// MARK: Fetch

	func fetchMagazine(request: MagazineDetail.FetchMagazine.Request)
	{

		let id = self.id
		let title = self.title
		let pdfUrl = self.pdfUrl

		if id != nil, pdfUrl != nil {
			magazineWorker.fetchMagazine(id: id!, pdfUrl: pdfUrl!){ (magazineDocument) -> Void in

				let response = MagazineDetail.FetchMagazine.Response(title: title!, pdfDocument: magazineDocument)
				self.presenter?.persentMagazine(response: response)
			}
		} else {
			print("pdf의 id 또는 url 누락")
		}
	}
}
