//
//  MagazineDetailModels.swift
//  PdfSample
//
//  Created by 60058232 on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PDFKit

enum MagazineDetail
{
  // MARK: Use cases
  
  enum FetchMagazine
  {
    struct Request
    {
    }
    struct Response
    {
		var title: String
		var pdfDocument: PDFDocument?
    }
    struct ViewModel
    {
		var title: String
		var pdfDocument: PDFDocument?
    }
  }
}
