//
//  MagazineDetailPresenter.swift
//  PdfSample
//
//  Created by 60058232 on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MagazineDetailPresentationLogic
{
  func persentMagazine(response: MagazineDetail.FetchMagazine.Response)
}

class MagazineDetailPresenter: MagazineDetailPresentationLogic
{
  weak var viewController: MagazineDetailDisplayLogic?
  
  // MARK: present magazine
  
  func persentMagazine(response: MagazineDetail.FetchMagazine.Response)
  {
	let viewModel = MagazineDetail.FetchMagazine.ViewModel(title: response.title, pdfDocument: response.pdfDocument)
    viewController?.displayMagazine(viewModel: viewModel)
  }
}
