//
//  MagazineDetailViewController.swift
//  PdfSample
//
//  Created by 60058232 on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PDFKit

protocol MagazineDetailDisplayLogic: class
{
	func displayMagazine(viewModel: MagazineDetail.FetchMagazine.ViewModel)
}

class MagazineDetailViewController: UIViewController, UIPageViewControllerDelegate, MagazineDetailDisplayLogic {

	var interactor: MagazineDetailBusinessLogic?
	var router: (NSObjectProtocol & MagazineDetailRoutingLogic & MagazineDetailDataPassing)?

	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?){
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder)
	{
		super.init(coder: aDecoder)
		setup()
	}


	// MARK: - Setup

	private func setup()
	{
		let viewController = self
		let interactor = MagazineDetailInteractor()
		let presenter = MagazineDetailPresenter()
		let router = MagazineDetailRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

	// MARK: - Routing

	override func prepare(for segue: UIStoryboardSegue, sender: Any?)
	{
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}

	// MARK: View lifecycle

	override func viewDidLoad()
	{
		super.viewDidLoad()
		setPDFView()
		fetchMagazine()
	}

	// MARK: - Fetch magazine

	var pdfView : PDFView?

	func setPDFView(){
		pdfView = PDFView(frame: self.view.bounds)
		if pdfView != nil {
			pdfView?.autoresizingMask = [.flexibleWidth, .flexibleHeight]
			self.view.addSubview(pdfView!)
			pdfView?.autoScales = true
		}
	}

	func fetchMagazine()
	{
		let request = MagazineDetail.FetchMagazine.Request()
		interactor?.fetchMagazine(request: request)
	}

	func displayMagazine(viewModel: MagazineDetail.FetchMagazine.ViewModel)
	{
		self.navigationController?.navigationBar.topItem?.title = viewModel.title
		pdfView?.document = viewModel.pdfDocument
	}


	// MARK: - Page Controller

	var pageViewController : UIPageViewController?
	var modelController: ModelController?

	func setPageController(){

		pageViewController = UIPageViewController(transitionStyle: .pageCurl, navigationOrientation: .horizontal, options: nil)
		modelController = ModelController()

		if let pageVC = pageViewController, let mController = modelController {

			pageVC.delegate = self
			let firstVC = mController.viewControllerAtIndex(0, storyboard: self.storyboard!) as DataViewController
			let VCs : [DataViewController] = [firstVC]

			pageVC.setViewControllers(VCs, direction: .forward, animated: false, completion: nil)
			pageVC.dataSource = mController

			self.addChild(pageVC)
			self.view.addSubview(pageVC.view)

			let pageViewRect = self.view.bounds
			pageVC.view.frame = pageViewRect
			pageVC.didMove(toParent: self)

			self.view.gestureRecognizers = pageVC.gestureRecognizers

		} else {
			return
		}
	}


	func pageViewController(_ pageViewController: UIPageViewController, spineLocationFor orientation: UIInterfaceOrientation) -> UIPageViewController.SpineLocation {

		if orientation.isPortrait {
			let curVC = pageViewController.viewControllers![0] as UIViewController
			let VCs = [curVC]
			pageViewController.setViewControllers(VCs, direction: .forward, animated: true, completion: nil)
			pageViewController.isDoubleSided = false

			return .min
		}

		let curVC = self.pageViewController?.viewControllers?[0] as! DataViewController

		var vcPage : [UIViewController] = []
		guard let indexOfCurVC = modelController?.indexOfViewController(curVC) else { return .mid }

		if indexOfCurVC % 2 == 0 {
			let nextVC : UIViewController = modelController!.pageViewController(pageViewController, viewControllerAfter: curVC)!

			vcPage = [curVC, nextVC]
		} else {
			let preVC : UIViewController = modelController!.pageViewController(pageViewController, viewControllerBefore: curVC)!

			vcPage = [preVC, curVC]
		}

		pageViewController.setViewControllers(vcPage, direction: .forward, animated: true, completion: nil)

		return .mid
	}

}
