//
//  MagazineListRouter.swift
//  PdfSample
//
//  Created by 60058232 on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MagazineListRoutingLogic
{
	func routeToMagazineDetail(segue: UIStoryboardSegue?)
}

protocol MagazineListDataPassing
{
	var dataStore: MagazineListDataStore? { get }
}

class MagazineListRouter: NSObject, MagazineListRoutingLogic, MagazineListDataPassing
{
	weak var viewController: MagazineListViewController?
	var dataStore: MagazineListDataStore?

	// MARK: Routing

	func routeToMagazineDetail(segue: UIStoryboardSegue?)
	{
	  if let segue = segue {
	    let destinationVC = segue.destination as! MagazineDetailViewController
	    var destinationDS = destinationVC.router!.dataStore!
	    passDataToMagazineDetail(source: dataStore!, destination: &destinationDS)
	  } else {
	    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	    let destinationVC = storyboard.instantiateViewController(withIdentifier: "MagazineDetailViewController") as! MagazineDetailViewController
	    var destinationDS = destinationVC.router!.dataStore!
		passDataToMagazineDetail(source: dataStore!, destination: &destinationDS)
	    navigateToMagazineDetail(source: viewController!, destination: destinationVC)
	  }
	}

	// MARK: Navigation

	func navigateToMagazineDetail(source: MagazineListViewController, destination: MagazineDetailViewController)
	{
	  source.show(destination, sender: nil)
	}

	// MARK: Passing data

	func passDataToMagazineDetail(source: MagazineListDataStore, destination: inout MagazineDetailDataStore)
	{
		let indexPath : [IndexPath] = (viewController?.magazineCollectionView.indexPathsForSelectedItems)!

		let magazine = viewController?.magazineList[indexPath[0].row]
		destination.id = magazine?.id
		destination.title = magazine?.title
		destination.pdfUrl = magazine?.pdfUrl
	}
}
